
INSERT INTO STUDENT_POOL(ID, PROVINCE, STU_TYPE, BATCH)
    VALUES(1, '福建', '理科', 1);
INSERT INTO STUDENT_POOL(ID, PROVINCE, STU_TYPE, BATCH)
    VALUES(2, '福建', '文科', 1);


INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(1, 1, 2016, 465);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(2, 1, 2015, 525);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(3, 1, 2014, 506);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(4, 1, 2013, 501);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(5, 1, 2012, 546);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(6, 1, 2011, 573);
INSERT INTO BATCH_SCORE(ID, STUDENT_POOL_ID, YEAR, MIN_SCORE)
    VALUES(7, 1, 2010, 539);

